name: Security Code Scans & Semgrep

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Gradle
        run: ./gradlew --no-daemon --stacktrace --warning-mode all build

      - name: Ensure SARIF Directory Exists
        run: mkdir -p ./results

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: ./results/codeql.sarif

      - name: Debug CodeQL Output
        run: |
          echo "Checking CodeQL Output"
          ls -lah ./results
          cat ./results/codeql.sarif || echo "codeql.sarif not generated"

      - name: Upload CodeQL SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: ./results/codeql.sarif

  semgrep:
    name: Run Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep for Java
        run: semgrep --config=p/java --sarif --output ./results/semgrep.sarif || true

      - name: Debug Semgrep Output
        run: |
          echo "Checking Semgrep Output"
          ls -lah ./results
          cat ./results/semgrep.sarif || echo "semgrep.sarif not generated"

      - name: Upload Semgrep SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: ./results/semgrep.sarif
