name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Files Exist
        run: ls -la $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/src registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2 \
          semgrep --config auto --json --output /src/semgrep-report.json /src || echo "Semgrep failed, check errors"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.json
