name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Verify Files Exist
      #   run: ls -laR $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        run: |
          mkdir $ANALYZER_ARTIFACT_DIR/artifacts
          /analyzer run --target-dir $ANALYZER_ARTIFACT_DIR/rtifacts --artifact-dir  --ignored-dirs "" --max-depth 100 || echo "Semgrep finished with warnings"
          ls -la ANALYZER_ARTIFACT_DIR
          echo "Checking if report exists:"
          ls -la $ANALYZER_ARTIFACT_DIR/artifacts 

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /gl-sast-report.json
