name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Verify Files Exist
      #   run: ls -laR $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        if: "contains(github.workspace, '*.py') || contains(github.workspace, '*.js') || contains(github.workspace, '*.java') || contains(github.workspace, '*.ts') || contains(github.workspace, '*.tsx') || contains(github.workspace, '*.rb') || contains(github.workspace, '*.php') || contains(github.workspace, '*.c') || contains(github.workspace, '*.cpp') || contains(github.workspace, '*.go')"
        run: |
          /analyzer run --target-dir $GITHUB_WORKSPACE --artifact-dir $GITHUB_WORKSPACE/ --ignored-dirs "" --max-depth 100 || echo "Semgrep finished with warnings"
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /__w/VulnerableApp/VulnerableApp/gl-sast-report.json
