name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Verify Files Exist
      #   run: ls -laR $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        run: |
          # echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE" 
          /analyzer run --target-dir $GITHUB_WORKSPACE --artifact-dir $GITHUB_WORKSPACE/ --ignored-dirs "" --max-depth 100 || echo "Semgrep finished with warnings"
          # chmod 777 $GITHUB_WORKSPACE/gl-sast-report.json
          # echo "Checking if report exists:"
          # ls -la $GITHUB_WORKSPACE

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /__w/VulnerableApp/VulnerableApp/gl-sast-report.json
