name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find Relevant Files
        id: check_files
        run: |
          files=$(find $GITHUB_WORKSPACE -type f \( -name "*.py" -o -name "*.js" -o -name "*.java" -o -name "*.ts" -o -name "*.tsx" -o -name "*.rb" -o -name "*.php" -o -name "*.c" -o -name "*.cpp" -o -name "*.go" \))
          if [ -n "$files" ]; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Run Semgrep (Multi-Language Security Scan)
        if: env.found == 'true'
        run: |
          /analyzer run --target-dir $GITHUB_WORKSPACE --artifact-dir $GITHUB_WORKSPACE/ --ignored-dirs "" --max-depth 100 || echo "Semgrep finished with warnings"
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /__w/VulnerableApp/VulnerableApp/gl-sast-report.json
