name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Semgrep (Multi-Language Security Scan)
        run: docker run --rm -v $(pwd):/src registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2 semgrep --config auto --json --output ./results/semgrep-report.json /src

      - name: Upload Semgrep JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: ./results/semgrep.json
