name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Verify Files Exist
      #   run: ls -laR $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        run: |
          mkdir -p /tmp/artifacts
          echo "Scanning directory: $GITHUB_WORKSPACE"
          find $GITHUB_WORKSPACE -type f  # Log all files before scan
          /analyzer run --target-dir $GITHUB_WORKSPACE --artifact-dir /tmp/artifacts --ignored-dirs "" --max-depth 10 || echo "Semgrep finished with warnings"
          echo "Checking if report exists:"
          ls -la /tmp/artifacts
          cp /tmp/artifacts/gl-sast-report.json $GITHUB_WORKSPACE/gl-sast-report.json  # Ensure persistence

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: $GITHUB_WORKSPACE/gl-sast-report.json
