name: SAST Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Verify Files Exist
      #   run: ls -laR $GITHUB_WORKSPACE

      - name: Run Semgrep (Multi-Language Security Scan)
        run: |
          export CI_PROJECT_DIR=$GITHUB_WORKSPACE
          echo "Scanning directory: $CI_PROJECT_DIR"
          find $CI_PROJECT_DIR -type f  # Log all files before scan
          /analyzer run --target-dir $GITHUB_WORKSPACE --artifact-dir $CI_PROJECT_DIR --ignored-dirs "" --max-depth 100 || echo "Semgrep finished with warnings"
          echo "Checking if report exists:"
          find /tmp/artifacts -type f  # Log generated report files
          find $CI_PROJECT_DIR -type f  # Log all files after scan

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: $GITHUB_WORKSPACE/gl-sast-report.json
