name: Security Code Scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check for Java Source Files
        run: find . -name "*.java" || echo "No Java files found!"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build Project
        run: |
          if [ -f "mvnw" ]; then
            ./mvnw clean package -DskipTests
          elif [ -f "gradlew" ]; then
            ./gradlew build
          else
            echo "No build system found"
          fi

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: sarif

      - name: Upload CodeQL SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif
