  name: Semgrep Code Scan
  
  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  
  jobs:
    semgrep:
      name: Run Semgrep
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Run Semgrep
          uses: returntocorp/semgrep-action@v1
          with:
            config: "p/default"  # Uses Semgrep's default security rules
            args: "--sarif --output semgrep.sarif"
  
        - name: Ensure SARIF Report Exists
          run: ls -lah semgrep.sarif || echo "semgrep.sarif not found"
  
        - name: Upload Semgrep Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: semgrep-results
            path: semgrep.sarif
