name: Security Code Scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Gradle
        run: ./gradlew --no-daemon --stacktrace --warning-mode all build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: sarif

      - name: Upload CodeQL SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif
