name: Semgrep

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:      
  semgrep:
    name: Run Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep for Java
        run: semgrep --config=p/default --sarif --output ./results/semgrep.sarif || true

      - name: Debug Semgrep Output
        run: |
          echo "Checking Semgrep Output"
          ls -lah ./results
          cat ./results/semgrep.sarif || echo "semgrep.sarif not generated"
      - name: Upload Semgrep SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: ./results/semgrep.sarif
