name: Security Code Scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep with Custom Config
        run: semgrep --config=.semgrep.yml --sarif --output semgrep.sarif || true

      - name: Debug Semgrep Output
        run: |
          echo "Checking Semgrep Output"
          ls -lah
          cat semgrep.sarif || echo "semgrep.sarif not generated"

      - name: Upload Semgrep Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep.sarif

  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for uploading results
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java  # Change this based on your project (e.g., 'javascript', 'python')

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: sarif  # Generate SARIF file

      - name: Upload CodeQL SARIF Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif  # CodeQL generates a SARIF report
